from django.conf import settings

ADFORM_PM = settings.ADFORM_PM
ADFORM_ID = settings.ADFORM_ID
ADFORM_CART_ID = settings.ADFORM_CART_ID
ADFORM_PAYMENT_ID = settings.ADFORM_PAYMENT_ID
ADFORM_THANKYOU_ID = settings.ADFORM_THANKYOU_ID
ADFORM_PRODUCTPAGE_ID = settings.ADFORM_PRODUCTPAGE_ID

